### ISSUE TITLE
I can't see my own dumps

### ISSUE THREAD

**Issue by genodeftest** [abrt/faf#547] opened 2016-12-04 09:20 UTC
Steps to reproduce:
1. use gnome-abrt to report a bug. Sometimes it fails (lately, a lot) and upload the data to the retrace server
2. open the URL you got from gnome-abrt, e.g. https://retrace.fedoraproject.org/faf/dumpdirs/new/ccpp-2016-12-04-10:12:51-12803.tar.gz

What happens:
I can't see my own uploads

What should happen:
I should be able to see my own uploads at least to verify that they have been uploaded…

**Comment by xsuchy** [comment] 2017-05-03 13:56
Does it still happen to you? In that time we were having issue with storage and it may cause this issue. This has been recently resolved.

**Comment by genodeftest** [comment] 2017-05-03 14:12
For this (old) dump with the URL above, I can load the page but it just shows content that I could upload a new dump. I just uploaded 2 new dumps in the last 5 minutes and I've got the same issue. Also happens with a fresh Firefox profile. This is what the page looks like:
![faf-screenshot](https://cloud.githubusercontent.com/assets/934401/25664544/387fdcc8-301b-11e7-8f9f-13ace6898662.png)

**Comment by marusak** [comment] 2017-05-04 05:42
Could you introduce me into your workflow in more detail?
I just tried the whole reporting process in gnome abrt and everything seems to be working.
I will write my workflow and please let me know what we do differently so I can reproduce your problem.
1) Open gnome ABRT
2) In the left panel select some problem (ideally test this with some new problem)
3) a) Sometimes you can have a "Reports: ABRT server" there. It should send you to FAF to correct report
3) b) In the top right corner click report, and continue as it suggests. You should then see the link as in 3a.

Could you also provides us with the following data:
- version of gnome-abrt
- version of abrt
- version of libreport
- what package did crash?
- your operating system and release
- maybe archive the problem directory and send it to us. Please mind the sensitive data. You can send it to my email to mmarusak@redhat.com

**Comment by jfilak** [comment] 2017-05-04 17:51
@marusak This is about emergency analysis: https://github.com/abrt/libreport/blob/b1c8e4a33b4b2fc8e6c33cde9523758f014b6cba/doc/emergencyanalysis_event.conf.txt

**Comment by marusak** [comment] 2017-05-10 12:11
I've been in contact with @genodeftest and we talk about this. To also inform others whom this may concern:
It is not a bug in FAF, it is a feature. Reporting process failed (in component reporter-ureport) and therefore an "Emergency Analysis" was executed.

The site that is screenshot above is FAF's feature for reporting such dump dirs. However when gnome-abrt shows "upload" button instead of "ABRT server" is is very confusing for users who end up on that page. Therefore I propose updating the site a bit, so it displays some text what has happened.

Now the page looks like this:
![old](https://cloud.githubusercontent.com/assets/12330670/25897893/081cd102-358a-11e7-93bb-2b63f1c0531e.png)

I think that something like:
![one](https://cloud.githubusercontent.com/assets/12330670/25897911/164b72f6-358a-11e7-83f6-65277ebcf01d.png)
and
![two](https://cloud.githubusercontent.com/assets/12330670/25897917/1b254ffe-358a-11e7-8036-2dab31f20024.png)
would be nice. What do @genodeftest ,@jfilak and @xsuchy think about this? Is it more clear?

P.S. I am no UX designer, so please let me know how you want it to look like:)

**Comment by genodeftest** [comment] 2017-05-10 12:14
> What do @genodeftest, […] think about this? Is it more clear?

Yes, that is way more clear and a huge improvement.

I am no UX designer either, but I like the design except for one fact: The text could be left, why is it centered?

**Comment by xsuchy** [comment] 2017-05-10 12:21
@marusak I like it. And I think "contact developers" should be collapsed by default and the "upload dumpdir" expanded by default. I.e. your 3rd screenshot should be default.
And maybe you can elaborate more where they can find the tar.gz file.

**Comment by marusak** [comment] 2017-05-10 12:43
> I am no UX designer either, but I like the design except for one fact: The text could be left, why is it centered?

Well I thought center would be nicer. Isn't it?
![left](https://cloud.githubusercontent.com/assets/12330670/25898604/190fd95c-358d-11e7-80f8-44b3d18087da.png)

> @marusak I like it. And I think "contact developers" should be collapsed by default and the "upload dumpdir" expanded by default. I.e. your 3rd screenshot should be default.

No problem changing that. I'll put "contact developers" second and make it expanded by default.

> And maybe you can elaborate more where they can find the tar.gz file.

Yeah, I had that in my mind but then I forgot to write it there. Will change it.

**Comment by genodeftest** [comment] 2017-05-10 12:57
@marusak : Yes, center is nicer.

**Comment by marusak** [comment] 2017-07-10 08:35
I believe we can close this now. It was never an issue in FAF. The problem that the OP was hitting is described in https://bugzilla.redhat.com/show_bug.cgi?id=1319828

**Closed by marusak** 2017-07-10 08:35 UTC
Labels: bug
