### ISSUE TITLE
Return nonzero when reporting duplicate

### ISSUE THREAD

**Issue by martinky82** [abrt/faf#487] opened 2016-02-09 14:51 UTC
When the crash being reported has already been known to FAF, reporting shall return non zero code so the client has chance to stop further processing of the crash (like uploading full data etc.)

**Comment by mhabrnal** [comment] 2016-02-09 15:13
FAF server returns "problem is known" only if there exists a bugzilla related to the FAF report. 
In the case of QE FAF server, there are not links to the related bugzillas but links to problem dirs which are updated to an FTP server.

FAF server should be configurable to return "problem is known" not only if related bugzilla exist but, for example, even if URL to related problem data is known.

**Comment by mhabrnal** [comment] 2016-02-22 12:22
Close as duplicate of https://github.com/abrt/faf/issues/489

**Closed by mhabrnal** 2016-02-22 12:22 UTC
