### ISSUE TITLE
gnome -shell 

### ISSUE THREAD

**Issue by Softskills** [abrt/faf#648] opened 2018-04-30 15:36 UTC
![gnome-shell-bug](https://user-images.githubusercontent.com/5600826/39435475-ccabedc2-4c9b-11e8-9ee4-f68472dccea0.png)
On Fedora 28 4.16.4-300.fc28.x86_64
gnome-shell quit unexpectedly at start up. 
journalctl at 15:42 hours::
Apr 30 15:37:00 localhost.localdomain gnome-shell[4127]: Object Meta.WindowActor (0x5651d799eb90), has been already finalized. Impossible to set any property to it.
Apr 30 15:37:03 localhost.localdomain gnome-shell[4127]: Object St.Widget (0x5651d8201050), has been already finalized. Impossible to get any property from it.
Apr 30 15:37:03 localhost.localdomain gnome-shell[4127]: Object St.Widget (0x5651d8201050), has been already finalized. Impossible to set any property to it.
Apr 30 15:42:36 localhost.localdomain gnome-shell[4127]: Object Meta.WindowActor (0x5651d6827760), has been already finalized. Impossible to get any property from it.
Apr 30 15:42:36 localhost.localdomain gnome-shell[4127]: Object Meta.WindowActor (0x5651d6827760), has been already finalized. Impossible to set any property to it.
Apr 30 15:42:42 localhost.localdomain gnome-shell[4127]: Object Meta.WindowActor (0x5651d799e7b0), has been already finalized. Impossible to get any property from it.
Apr 30 15:42:42 localhost.localdomain gnome-shell[4127]: Object Meta.WindowActor (0x5651d799e7b0), has been already finalized. Impossible to set any property to it.
Apr 30 15:42:45 localhost.localdomain gnome-shell[4127]: The program 'gnome-shell' received an X Window System error.
Apr 30 15:42:45 localhost.localdomain audit[4127]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=4127 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=5 res=1
Apr 30 15:42:47 localhost.localdomain systemd-coredump[6399]: Process 4127 (gnome-shell) of user 1000 dumped core.
                                                              #1  0x00005651d3851b83 dump_gjs_stack_on_signal_handler (gnome-shell)
                                                              #19 0x00005651d38514d8 main (gnome-shell)
                                                              #21 0x00005651d385162a _start (gnome-shell)
Apr 30 15:42:49 localhost.localdomain dbus-daemon[980]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.131' (uid=42 pid=3697 comm="/usr/bin/gnome-shell " label="system_u:system_r:xdm_t:s0-s0:c0.c1023")
Apr 30 15:42:49 localhost.localdomain gnome-shell[3697]: Object Clutter.Clone (0x55e139720a70), has been already finalized. Impossible to get any property from it.
Apr 30 15:42:49 localhost.localdomain gnome-shell[3697]: Object Clutter.Clone (0x55e139720a70), has been already finalized. Impossible to set any property to it.
Apr 30 15:42:49 localhost.localdomain abrt-notification[6546]: Process 4127 (gnome-shell) crashed in dump_gjs_stack_on_signal_handler()
Apr 30 15:42:55 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.Daemon' unit='gvfs-daemon.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:56 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.17' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:56 localhost.localdomain at-spi-bus-launcher[6722]: dbus-daemon[6727]: Activating service name='org.a11y.atspi.Registry' requested by ':1.0' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:56 localhost.localdomain gnome-shell[6661]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 332]: reference to undefined property "MetaStage"
Apr 30 15:42:56 localhost.localdomain gnome-shell[6661]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 220]: reference to undefined property "MetaWindowGroup"
Apr 30 15:42:56 localhost.localdomain gnome-shell[6661]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.freedesktop.impl.portal.PermissionStore' unit='xdg-permission-store.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.Shell.CalendarServer' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gnome.evolution.dataserver.Sources5' unit='evolution-source-registry.service' requested by ':1.26' (uid=1000 pid=6775 comm="/usr/libexec/gnome-shell-calendar-server " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain gnome-shell[6661]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Apr 30 15:42:57 localhost.localdomain dbus-daemon[980]: [system] Activating via systemd: service name='org.freedesktop.GeoClue2' unit='geoclue.service' requested by ':1.303' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='ca.desrt.dconf' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain polkitd[1064]: Registered Authentication Agent for unix-session:6 (system bus name :1.303 [/usr/bin/gnome-shell], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.freedesktop.Telepathy.AccountManager' requested by ':1.30' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.UDisks2VolumeMonitor' unit='gvfs-udisks2-volume-monitor.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.MTPVolumeMonitor' unit='gvfs-mtp-volume-monitor.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.GoaVolumeMonitor' unit='gvfs-goa-volume-monitor.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.GPhoto2VolumeMonitor' unit='gvfs-gphoto2-volume-monitor.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.AfcVolumeMonitor' unit='gvfs-afc-volume-monitor.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:57 localhost.localdomain gnome-shell[6661]: Extension "tracker-search@cewee" had error: ImportError: No JS module 'searchDisplay' found in search path
Apr 30 15:42:57 localhost.localdomain gnome-shell[6661]: loading default theme (Adwaita)
Apr 30 15:42:57 localhost.localdomain gnome-shell[6661]: Extension user-theme@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Extension alternate-tab@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/alternate-tab@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Extension apps-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Extension launch-new-instance@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Extension places-menu@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Extension window-list@gnome-shell-extensions.gcampax.github.com already installed in /home/jaap/.local/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com. /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com will not be loaded
Apr 30 15:42:58 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gnome.evolution.dataserver.Calendar7' unit='evolution-calendar-factory.service' requested by ':1.26' (uid=1000 pid=6775 comm="/usr/libexec/gnome-shell-calendar-server " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Object St.Widget (0x563a15c28ef0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Apr 30 15:42:58 localhost.localdomain org.gnome.Shell.desktop[6661]: #0 0x563a14418458 i   /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org/extension.js:232 (0x7fd4140e0120 @ 15)
Apr 30 15:42:58 localhost.localdomain org.gnome.Shell.desktop[6661]: #2 0x563a144183d8 i   /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org/extension.js:232 (0x7fd4140e0098 @ 17)
Apr 30 15:42:58 localhost.localdomain org.gnome.Shell.desktop[6661]: #3 0x563a14418358 i   /usr/share/gnome-shell/extensions/background-logo@fedorahosted.org/extension.js:225 (0x7fd4140ceef0 @ 10)
Apr 30 15:42:58 localhost.localdomain gnome-shell[6661]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Apr 30 15:42:58 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:42:59 localhost.localdomain gnome-shell[6661]: STACK_OP_ADD: window 0x1800001 already in stack
Apr 30 15:42:59 localhost.localdomain gnome-shell[6661]: STACK_OP_ADD: window 0x1800001 already in stack
Apr 30 15:42:59 localhost.localdomain gnome-shell[6661]: Theme file for Breeze_Snow has no directories
Apr 30 15:43:00 localhost.localdomain gnome-shell[6661]: GNOME Shell started at Mon Apr 30 2018 15:42:57 GMT+0200 (CEST)
Apr 30 15:43:12 localhost.localdomain gnome-shell[6661]: Object St.Widget (0x563a14621480), has been already finalized. Impossible to get any property from it.
Apr 30 15:43:12 localhost.localdomain gnome-shell[6661]: Object St.Widget (0x563a14621480), has been already finalized. Impossible to set any property to it.
Apr 30 15:43:40 localhost.localdomain gnome-shell[6661]: The property brightness doesn't seem to be a normal object property of [0x563a1648bc40 StWidget] or a registered special property
Apr 30 15:43:40 localhost.localdomain gnome-shell[6661]: The property vignette_sharpness doesn't seem to be a normal object property of [0x563a1648bc40 StWidget] or a registered special property
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.ControlCenter.SearchProvider' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.Contacts.SearchProvider' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.Nautilus' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.Calculator.SearchProvider' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.Calendar' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating service name='org.gnome.clocks' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Apr 30 15:43:41 localhost.localdomain dbus-daemon[6574]: [session uid=1000 pid=6574] Activating via systemd: service name='org.gnome.GPaste' unit='org.gnome.GPaste.service' requested by ':1.14' (uid=1000 pid=6661 comm="/usr/bin/gnome-shell " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")

**Comment by marusak** [comment] 2018-05-01 06:51
Hi,

I don't understand how is this a FAF (or ABRT) issue. ABRT is tool that catches problems that happen in your system and enables you to report them in different ways. In your case gnome-shell crashed, ABRT caught it. FAF is tool that collects anonymous reports to help developers recognize how many problems their components have.

If I missed the issue you are trying to report, feel free to reopen, but I'm closing as not a bug.

**Closed by marusak** 2018-05-01 06:51 UTC
