### ISSUE TITLE
Exclude Taint Flags not excluding kernel backtraces

### ISSUE THREAD

**Issue by labbott** [abrt/faf#474] opened 2015-10-26 23:15 UTC
When I select all the taint flags for exclusion in the kernel component, I'm still seeing backtraces show up in the filtered results up that have taint flags.set (e.g. https://retrace.fedoraproject.org/faf/problems/bthash/?bth=1517be5dfa26e0878a6310a36537fefed84a4307&bth=258b663c8da425efa9d8999b4e52fe52681527e3&bth=3c751ce0431cd0ceff63d3df0fd994e2879c5bf3&bth=5c04041707a05044fe5c67911fa5b35ac4075389&bth=790b05e866b498d8bc31d48609a0023d2beb2b3b&bth=9476d530b1dfd9fc4d41c272e97e7f381e440866&bth=bc05be7a80bdc30aa38cb93407aaba03a12a58d5&bth=c3f50a8d076dbb5c15a240f1ee2e6f9721b7e36e&bth=d640a5559d85f19704a4b8c35d04ac06de7aa8f8&bth=e31c612cd5750b829bc9cd877b66e6182e9ae986 )

**Comment by marusak** [comment] 2017-07-14 09:33
I investigate on this a bit and I found that all problems are found, which contain **at least one** report that **does not have** a taint flag.
Question now is whether it is bug or feature:) I believe it is a feature, since you have at least one report that is not tainted.
What is your option? @labbott @jfilak @sorki

**Comment by marusak** [comment] 2017-11-13 21:37
Closing as not a bug. Feel free to reopen and provide me with more information:)

**Closed by marusak** 2017-11-13 21:37 UTC
Labels: bug
