### ISSUE TITLE
RPM needs to be updated

### ISSUE THREAD

**Issue by silviucc** [abrt/faf#875] opened 2020-02-16 11:35 UTC
Hello,

I want to report a crash for latest wine package (5.1) but can't because it always fails. I was looking through the log it seems to fail to install relevant rpm files because it's not using the correct version of RPM.
[abrt_failed_retrace.zip](https://github.com/abrt/faf/files/4209696/abrt_failed_retrace.zip)

**Comment by ernestask** [comment] 2020-02-16 11:37
Duplicate of #839

**Closed** 2020-02-16 11:37 UTC
